# Файл docker-compose.yml
volumes:
  pg_data:
  # Новый volume — для статических файлов
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    # Тут подключаем volume к backend
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/

# Добавляем новый контейнер: gateway
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    build: ./gateway/
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles
    depends_on:
      - backend
    ports:
      - 8000:80
